#file: noinspection UndefinedParamsPresent
name: Run tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}+${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, nightly, 1.46.0, 1.56.0, 1.64]
        include:
          - rust: 1.46.0
            features: full_msrv, dev
          - rust: 1.56.0
            features: full_msrv, dev
          - rust: 1.64
            features: full, dev
          - rust: stable
            features: full, dev
          - rust: nightly
            features: full_nightly, dev

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        id: install_rust
        uses: dtolnay/rust-toolchain@master
        continue-on-error: true
        with:
          toolchain: ${{ matrix.rust }}
          components: ${{ matrix.rust == 'nightly' && 'miri' || '' }}

      - name: Run all tests
        if: steps.install_rust.outcome == 'success'
        continue-on-error: false
        run: cargo +${{ matrix.rust }} test --verbose --features ${{ matrix.features }}

      - name: Run Miri
        if: matrix.rust == 'nightly' && steps.install_rust.outcome == 'success'
        continue-on-error: false
        env:
          MIRIFLAGS: -Zmiri-permissive-provenance
        run: cargo +${{ matrix.rust }} miri test --verbose --features ${{ matrix.features }}
